const actionTypes = {
  REGISTER_SUCCESS: "REGISTER",
  REGISTER_FAIL: "REGISTER",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN",
  LOGIN_FAIL: "LOGIN",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POST: "GET_NEW_POST",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICE: "GET_PRICE",
  GET_AREA: "GET_AREA",
};

export default actionTypes;
