const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_POST_ADMIN: "GET_POST_ADMIN",
  GET_NEW_POST: "GET_NEW_POST",
  EDIT_DATA: "EDIT_DATA",
  RESET_DATAEDIT: "RESET_DATAEDIT",
  GET_OUTSTANDING: "GET_OUTSTANDING",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICE: "GET_PRICE",
  GET_AREA: "GET_AREA",
  GET_PROVINCE: "GET_PROVINCE",
  //USER
  GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
